// Barrina Gardens CRM — Master Data Layer
// Source: DMF-089 spreadsheet (11 Feb 2026) + resident files
// DO NOT edit manually — regenerate from source spreadsheet

export type UnitStatus = 'Occupied' | 'Vacant' | 'Under Maintenance' | 'Reserved';
export type ContractType = 'New' | 'D' | 'C' | 'Loan Lease' | 'Old';
export type ResidentStatus = 'Active' | 'Departed' | 'Deceased' | 'On Leave';
export type EnquiryStatus = 'Active' | 'Waitlist' | 'No Longer Interested' | 'Sold';
export type TaskStatus = 'Open' | 'In Progress' | 'Completed' | 'Overdue';
export type TaskPriority = 'Low' | 'Medium' | 'High' | 'Urgent';
export type MaintenanceStatus = 'Logged' | 'Assigned' | 'In Progress' | 'Completed' | 'Deferred';
export type ContactLogType = 'SMS' | 'Phone Call' | 'Attempted Contact' | 'Email' | 'In-Person Meeting';
export type AppointmentType = 'Village Tour' | 'Legal Meeting' | 'Fire Safety Inspection' | 'Medical Review' | 'Maintenance Inspection' | 'General Meeting' | 'Other';

export interface FieldHistoryEntry {
  id: string;
  field: string;
  oldValue: string;
  newValue: string;
  changedBy: string;
  changedAt: string;
}

export interface Note {
  id: string;
  text: string;
  author: string;
  createdAt: string;
  type?: string;
}

export interface ContactLogEntry {
  id: string;
  type: ContactLogType;
  subType?: string;
  notes: string;
  author: string;
  createdAt: string;
}

export interface EmergencyContact {
  title?: string;
  firstName?: string;
  lastName?: string;
  mobile?: string;
  email?: string;
  relationship?: string;
  address?: string;
}

export interface Resident {
  id: string;
  title?: string;
  firstName: string;
  lastName: string;
  preferredName?: string;
  email?: string;
  mobile?: string;
  dob?: string;
  gender?: string;
  medicareNo?: string;
  ambulanceNo?: string;
  healthFund?: string;
  healthFundNo?: string;
  drName?: string;
  drClinic?: string;
  drPhone?: string;
  drEmail?: string;
  lawyerFirm?: string;
  lawyerName?: string;
  poaHolder?: string;
  medicalConditions?: string;
  allergies?: string;
  medications?: string[];
  ec1?: EmergencyContact;
  ec2?: EmergencyContact;
  hasPet?: boolean;
  petType?: string;
  petBreed?: string;
  status?: ResidentStatus;
  photo?: string;
  notes?: Note[];
  fieldHistory?: FieldHistoryEntry[];
}

export interface Unit {
  unitNo: string;
  status: UnitStatus;
  unitType: string;
  unitStyle: string;
  landSqm: number;
  address: string;
  suburb: string;
  state: string;
  postcode: string;
  ownership: string;
  contractType: string;
  settlementPrice: number;
  settlementDate: string;
  marketValue: number;
  yearsOwned: number;
  dmfRate: number;
  annualDmf: number;
  nonAccDmf?: number | null;
  totalDeferred: number;
  careAlertPhone: string;
  simMobile?: string;
  ownerName: string;
  gender?: string;
  dob?: string;
  age?: string;
  numResidents?: number;
  comments?: string;
  photos?: string[];
  medicalFiles?: string[];
  isDeceased?: boolean;
  isForSale?: boolean;
  residents?: Resident[];
  notes?: Note[];
  fieldHistory?: FieldHistoryEntry[];
}

export interface Lead {
  id: string;
  firstName: string;
  lastName: string;
  phone?: string;
  email?: string;
  address?: string;
  currentAddress?: string;
  ownsProperty?: boolean;
  preferredCallbackTime?: string;
  desiredUnitStyle?: string;
  budget?: number;
  notes?: Note[];
  contactLog?: ContactLogEntry[];
  callbackDate?: string;
  assignedTo?: string;
  leadSource?: string;
  status: EnquiryStatus;
  createdAt: string;
  fieldHistory?: FieldHistoryEntry[];
}

export interface WaitlistEntry {
  id: string;
  firstName: string;
  lastName: string;
  phone?: string;
  email?: string;
  desiredUnitStyle?: string;
  budget?: number;
  callbackDate?: string;
  assignedTo?: string;
  notes?: Note[];
  createdAt: string;
  priority?: number;
}

export interface Task {
  id: string;
  title: string;
  description?: string;
  status: TaskStatus;
  priority: TaskPriority;
  category?: string;
  assignedTo?: string;
  dueDate?: string;
  createdAt: string;
  completedAt?: string;
  relatedTo?: string;
  relatedType?: string;
  notes?: Note[];
}

export interface MaintenanceRequest {
  id: string;
  unitNo: string;
  title: string;
  description?: string;
  status: MaintenanceStatus;
  priority: TaskPriority;
  reportedBy?: string;
  assignedTo?: string;
  createdAt: string;
  completedAt?: string;
  notes?: Note[];
}

export interface Appointment {
  id: string;
  title: string;
  type: AppointmentType;
  date: string;
  time: string;
  contactName?: string;
  contactPhone?: string;
  contactEmail?: string;
  location?: string;
  notes?: string;
  createdBy?: string;
  createdAt: string;
}

export interface SimCard {
  unitNo: string;
  residentName: string;
  mobileNumber: string;
  provider?: string;
  status?: string;
}

export const units: Unit[] = [
  {
    unitNo: "1",
    status: "Occupied",
    unitType: "2 Bedroom",
    unitStyle: "Open Plan",
    landSqm: 130.5,
    address: "Unit 1 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "New",
    settlementPrice: 520000,
    settlementDate: "2024-06-17",
    marketValue: 570000,
    yearsOwned: 1.72,
    dmfRate: 0.03,
    annualDmf: 17100,
    totalDeferred: 29402.5,
    careAlertPhone: "0401 909 506",
    ownerName: "Eustace (Bill) & Shirley Cole",
    gender: "M&F",
    dob: "Eustace 06/06/1938 - Shirley 21/09/1944",
    age: "85 & 79",
    numResidents: 2,
    photos: ["/assets/photos/U43-BillandShirleyCole.jpg"],
    medicalFiles: ["/assets/medical/Unit1.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "2",
    status: "Occupied",
    unitType: "2 Bedroom",
    unitStyle: "Classic",
    landSqm: 127.9,
    address: "Unit 2 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "D",
    settlementPrice: 390000,
    settlementDate: "2018-10-25",
    marketValue: 500000,
    yearsOwned: 7.36,
    dmfRate: 0.03,
    annualDmf: 15000,
    totalDeferred: 110458.33,
    careAlertPhone: "0401 932 815",
    ownerName: "Kevin Stewart",
    gender: "M",
    dob: "1961-09-15",
    age: "64.51506849315068",
    numResidents: 1,
    medicalFiles: ["/assets/medical/Unit2.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "3",
    status: "Occupied",
    unitType: "1 Bedroom",
    unitStyle: "Classic",
    landSqm: 111.6,
    address: "Unit 3 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "New",
    settlementPrice: 370000,
    settlementDate: "2024-12-20",
    marketValue: 395000,
    yearsOwned: 1.21,
    dmfRate: 0.03,
    annualDmf: 11850,
    totalDeferred: 14351.67,
    careAlertPhone: "0401 972 050",
    ownerName: "Anthony (Tony) Castellano",
    gender: "M",
    dob: "1960-07-29",
    age: "65.64657534246575",
    numResidents: 1,
    photos: ["/assets/photos/U03-AnneBlair.JPEG"],
    medicalFiles: ["/assets/medical/Unit3.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "4",
    status: "Occupied",
    unitType: "1 Bedroom",
    unitStyle: "Classic",
    landSqm: 117.91,
    address: "Unit 4 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "C",
    settlementPrice: 290000,
    settlementDate: "2015-03-27",
    marketValue: 395000,
    yearsOwned: 10.94,
    dmfRate: 0.03,
    annualDmf: 0,
    nonAccDmf: 11850,
    totalDeferred: 118500,
    careAlertPhone: "0401 971 941",
    ownerName: "Geoffrey Auton",
    gender: "M",
    dob: "1943-10-16",
    age: "82.44383561643835",
    numResidents: 1,
    photos: ["/assets/photos/U04-GeoffreyAuton.jpg"],
    medicalFiles: ["/assets/medical/Unit4.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "5",
    status: "Occupied",
    unitType: "1 Bedroom",
    unitStyle: "Classic",
    landSqm: 175.27,
    address: "Unit 5 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "Loan Lease",
    settlementPrice: 440000,
    settlementDate: "2024-07-22",
    marketValue: 440000,
    yearsOwned: 1.62,
    dmfRate: 0.03,
    annualDmf: 13200,
    totalDeferred: 21413.33,
    careAlertPhone: "0401 969 740",
    ownerName: "Dianne Leslie",
    gender: "F",
    dob: "1944-07-30",
    age: "81.65479452054795",
    numResidents: 1,
    medicalFiles: ["/assets/medical/Unit5.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "6",
    status: "Vacant",
    unitType: "1 Bedroom",
    unitStyle: "Classic",
    landSqm: 118.42,
    address: "Unit 6 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "N/A",
    settlementPrice: 295000,
    settlementDate: "2022-07-05",
    marketValue: 395000,
    yearsOwned: 3.67,
    dmfRate: 0,
    annualDmf: 0,
    totalDeferred: 0,
    careAlertPhone: "0401 969 537",
    ownerName: "BGP Owned",
    gender: "F",
    dob: "1948-09-12",
    age: "77.53150684931506",
    numResidents: 1,
    comments: "Under offer - 395k",
    photos: ["/assets/photos/U06-MaureenCostelloe.jpg"],
    medicalFiles: ["/assets/medical/Unit6(Empty).jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "7",
    status: "Occupied",
    unitType: "1 Bedroom",
    unitStyle: "Classic",
    landSqm: 119.69,
    address: "Unit 7 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "Loan Lease",
    settlementPrice: 295000,
    settlementDate: "2025-11-28",
    marketValue: 395000,
    yearsOwned: 0.27,
    dmfRate: 0.03,
    annualDmf: 11850,
    totalDeferred: 3225.83,
    careAlertPhone: "0401 969 390",
    ownerName: "Myf Macfarlane ",
    gender: "N/A",
    dob: "1943-12-25",
    age: "82.25205479452055",
    numResidents: 1,
    medicalFiles: ["/assets/medical/Unit7(Empty).jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "8",
    status: "Occupied",
    unitType: "2 Bedroom",
    unitStyle: "Open Plan",
    landSqm: 139.62,
    address: "Unit 8 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "C",
    settlementPrice: 375000,
    settlementDate: "2021-09-30",
    marketValue: 550000,
    yearsOwned: 4.43,
    dmfRate: 0.03,
    annualDmf: 16500,
    totalDeferred: 73150,
    careAlertPhone: "0401 968 388",
    ownerName: "Cheryl Dabrera",
    gender: "F",
    dob: "1948-09-16",
    age: "77.52054794520548",
    numResidents: 1,
    photos: ["/assets/photos/U08-CherylDabrera.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "9",
    status: "Occupied",
    unitType: "2 Bedroom + Carport",
    unitStyle: "Classic",
    landSqm: 138.1,
    address: "Unit 9 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "D",
    settlementPrice: 379000,
    settlementDate: "2020-09-28",
    marketValue: 525000,
    yearsOwned: 5.44,
    dmfRate: 0.03,
    annualDmf: 15750,
    totalDeferred: 85662.5,
    careAlertPhone: "0401 967 501",
    ownerName: "Margaret White",
    gender: "F",
    dob: "1939-12-14",
    age: "86.28493150684932",
    numResidents: 1,
    photos: ["/assets/photos/U09-MargaretWhite.jpg"],
    medicalFiles: ["/assets/medical/Unit9.jpg", "/assets/medical/Unit9B.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "10",
    status: "Occupied",
    unitType: "2 Bedroom",
    unitStyle: "Classic",
    landSqm: 139.13,
    address: "Unit 10 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "C",
    settlementPrice: 380000,
    settlementDate: "2020-11-20",
    marketValue: 520000,
    yearsOwned: 5.29,
    dmfRate: 0.03,
    annualDmf: 15600,
    totalDeferred: 82593.33,
    careAlertPhone: "0401 934 760",
    ownerName: "Lesley Soxsmith",
    gender: "F",
    dob: "1946-08-10",
    age: "79.62465753424658",
    numResidents: 1,
    photos: ["/assets/photos/U10-LesleySoxsmith.JPEG"],
    medicalFiles: ["/assets/medical/Unit10.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "11",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Carport",
    unitStyle: "Classic",
    landSqm: 169.53,
    address: "Unit 11 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "New",
    settlementPrice: 600000,
    settlementDate: "2025-10-21",
    marketValue: 620000,
    yearsOwned: 0.38,
    dmfRate: 0.03,
    annualDmf: 18600,
    totalDeferred: 6975,
    careAlertPhone: "0401 932 001",
    ownerName: "Maree Wright",
    gender: "F",
    dob: "1935-06-06",
    age: "90.81095890410958",
    numResidents: 1,
    photos: ["/assets/photos/U11-MargaretRobins.JPEG"],
    medicalFiles: ["/assets/medical/Unit11.jpg", "/assets/medical/Unit11B.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "12",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Carport",
    unitStyle: "Classic",
    landSqm: 168.53,
    address: "Unit 12 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "Loan Lease",
    settlementPrice: 540000,
    settlementDate: "2022-08-08",
    marketValue: 620000,
    yearsOwned: 3.58,
    dmfRate: 0.03,
    annualDmf: 18600,
    totalDeferred: 66546.67,
    careAlertPhone: "0401 930 455",
    ownerName: "Carole & Meriel Barber",
    gender: "F&F",
    dob: "28/04/1961&11/06/1938",
    age: "63 & 86",
    numResidents: 2,
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "13",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Carport",
    unitStyle: "Classic",
    landSqm: 176.15,
    address: "Unit 13 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "C",
    settlementPrice: 437500,
    settlementDate: "2012-04-26",
    marketValue: 620000,
    yearsOwned: 13.86,
    dmfRate: 0.03,
    annualDmf: 0,
    nonAccDmf: 18600,
    totalDeferred: 186000,
    careAlertPhone: "0401 927 229",
    ownerName: "Lucy Lynch",
    gender: "F",
    dob: "1933-08-04",
    age: "92.64931506849315",
    numResidents: 1,
    photos: ["/assets/photos/U13-LucyLynch.JPEG"],
    medicalFiles: ["/assets/medical/Unit13.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "14",
    status: "Occupied",
    unitType: "2 Bedroom + Study",
    unitStyle: "Classic",
    landSqm: 156.84,
    address: "Unit 14 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "Loan Lease",
    settlementPrice: 575000,
    settlementDate: "2022-07-14",
    marketValue: 600000,
    yearsOwned: 3.64,
    dmfRate: 0.03,
    annualDmf: 18000,
    totalDeferred: 65600,
    careAlertPhone: "0401 922 614",
    ownerName: "Lucy Ferris",
    gender: "F",
    dob: "1949-12-11",
    age: "76.28493150684932",
    numResidents: 1,
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "15",
    status: "Occupied",
    unitType: "2 Bedroom + Study",
    unitStyle: "Classic",
    landSqm: 192.77,
    address: "Unit 15 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "New",
    settlementPrice: 455000,
    settlementDate: "2025-02-19",
    marketValue: 575000,
    yearsOwned: 1.05,
    dmfRate: 0.03,
    annualDmf: 17250,
    totalDeferred: 18064.58,
    careAlertPhone: "0401 908 530",
    ownerName: "Ilona Mc Lauchlan",
    gender: "",
    dob: "1950-10-15",
    age: "75.44109589041096",
    numResidents: 1,
    medicalFiles: ["/assets/medical/Unit15.jpg", "/assets/medical/Unit15B.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "16",
    status: "Occupied",
    unitType: "2 Bedroom",
    unitStyle: "Open Plan",
    landSqm: 126.46,
    address: "Unit 16 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "D",
    settlementPrice: 460000,
    settlementDate: "2021-08-31",
    marketValue: 575000,
    yearsOwned: 4.52,
    dmfRate: 0.03,
    annualDmf: 17250,
    totalDeferred: 77912.5,
    careAlertPhone: "0401 960 975",
    ownerName: "Kaye Wood",
    gender: "F",
    dob: "1942-04-27",
    age: "83.91506849315068",
    numResidents: 1,
    photos: ["/assets/photos/U16-KayeWood.JPEG"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "17",
    status: "Occupied",
    unitType: "2 Bedroom + Garage",
    unitStyle: "Classic",
    landSqm: 129.75,
    address: "Unit 17 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "D",
    settlementPrice: 360000,
    settlementDate: "2015-11-26",
    marketValue: 620000,
    yearsOwned: 10.28,
    dmfRate: 0.03,
    annualDmf: 0,
    nonAccDmf: 18600,
    totalDeferred: 186000,
    careAlertPhone: "0401 930 063",
    ownerName: "Sheila Turner",
    gender: "F",
    dob: "1938-08-31",
    age: "87.57260273972602",
    numResidents: 1,
    photos: ["/assets/photos/U17-SheilaTurner.JPEG"],
    medicalFiles: ["/assets/medical/Unit17.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "18",
    status: "Occupied",
    unitType: "2 Bedroom",
    unitStyle: "Classic",
    landSqm: 137.91,
    address: "Unit 18 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "New",
    settlementPrice: 430000,
    settlementDate: "2025-02-20",
    marketValue: 500000,
    yearsOwned: 1.04,
    dmfRate: 0.03,
    annualDmf: 15000,
    totalDeferred: 15666.67,
    careAlertPhone: "0401 906 217",
    ownerName: "Mary Gledhill",
    gender: "F",
    dob: "1948-08-19",
    age: "78",
    numResidents: 1,
    medicalFiles: ["/assets/medical/Unit18.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "19",
    status: "Occupied",
    unitType: "2 Bedroom + Garage",
    unitStyle: "Open Plan",
    landSqm: 134.66,
    address: "Unit 19 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "Loan Lease",
    settlementPrice: 550000,
    settlementDate: "2024-07-26",
    marketValue: 620000,
    yearsOwned: 1.61,
    dmfRate: 0.03,
    annualDmf: 18600,
    totalDeferred: 29966.67,
    careAlertPhone: "0401 906 068",
    ownerName: "Clive & Jeanne Williams",
    gender: "M&F",
    dob: "Clive - 30/11/1946 & Jeanne: 26/01/1948",
    age: "78 & 76",
    numResidents: 2,
    medicalFiles: ["/assets/medical/Unit19.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "20",
    status: "Occupied",
    unitType: "2 Bedroom + Carport",
    unitStyle: "Classic",
    landSqm: 142.75,
    address: "Unit 20 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "A",
    settlementPrice: 265000,
    settlementDate: "2007-07-06",
    marketValue: 525000,
    yearsOwned: 18.67,
    dmfRate: 0.025,
    annualDmf: 0,
    nonAccDmf: 15750,
    totalDeferred: 131250,
    careAlertPhone: "0401 885 570",
    ownerName: "Elizabeth Lawrence",
    gender: "F",
    dob: "1933-09-15",
    age: "92.53424657534246",
    numResidents: 1,
    photos: ["/assets/photos/U20-ElizabethLawrence.jpg"],
    medicalFiles: ["/assets/medical/Unit20.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "21",
    status: "Occupied",
    unitType: "2 Bedroom + Carport",
    unitStyle: "Open Plan",
    landSqm: 132.69,
    address: "Unit 21 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "Loan Lease",
    settlementPrice: 500000,
    settlementDate: "2022-07-07",
    marketValue: 600000,
    yearsOwned: 3.66,
    dmfRate: 0.03,
    annualDmf: 18000,
    totalDeferred: 65950.0,
    careAlertPhone: "0401 929 068",
    ownerName: "Edna Lee",
    gender: "F",
    dob: "1947-09-29",
    age: "78.4876712328767",
    numResidents: 1,
    photos: ["/assets/photos/U21-EdnaLee.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "22",
    status: "Occupied",
    unitType: "2 Bedroom",
    unitStyle: "Classic",
    landSqm: 139.86,
    address: "Unit 22 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "C",
    settlementPrice: 395000,
    settlementDate: "2018-11-12",
    marketValue: 500000,
    yearsOwned: 7.32,
    dmfRate: 0.03,
    annualDmf: 15000,
    totalDeferred: 109750.0,
    careAlertPhone: "0401 922 047",
    ownerName: "Vyvyan Nielsen",
    gender: "F",
    dob: "1943-01-08",
    age: "78",
    numResidents: 1,
    photos: ["/assets/photos/U22-VyvyanNielsen.JPEG"],
    medicalFiles: ["/assets/medical/Unit22.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "23",
    status: "Occupied",
    unitType: "2 Bedroom",
    unitStyle: "Classic",
    landSqm: 136.22,
    address: "Unit 23 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "C",
    settlementPrice: 375000,
    settlementDate: "2017-05-12",
    marketValue: 575000,
    yearsOwned: 8.82,
    dmfRate: 0.03,
    annualDmf: 17250,
    totalDeferred: 152087.5,
    careAlertPhone: "0401 920 624",
    ownerName: "Henry Thorburn (higher care)",
    gender: "M",
    dob: "1934-07-06",
    age: "91.72876712328767",
    numResidents: 1,
    comments: "FOR SALE",
    medicalFiles: ["/assets/medical/Unit23.jpg"],
    isForSale: true,
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "24",
    status: "Vacant",
    unitType: "2 Bedroom",
    unitStyle: "Classic",
    landSqm: 126.71,
    address: "Unit 24 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "B",
    settlementPrice: 280000,
    settlementDate: "2008-06-30",
    marketValue: 550000,
    yearsOwned: 17.68,
    dmfRate: 0.03,
    annualDmf: 0,
    nonAccDmf: 16500,
    totalDeferred: 165000,
    careAlertPhone: "0401 914 286",
    ownerName: "Kay Allan (Deceased)",
    gender: "F",
    dob: "1938-10-03",
    age: "87.48219178082192",
    numResidents: 1,
    comments: "SOLD- Lisa (Derik son) 550k \nSettles 23rd April 2026",
    photos: ["/assets/photos/U24-KayeAllan.JPEG"],
    medicalFiles: ["/assets/medical/Unit24.jpg"],
    isDeceased: true,
    isForSale: true,
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "25",
    status: "Occupied",
    unitType: "2 Bedroom + Garage",
    unitStyle: "Open Plan",
    landSqm: 200.06,
    address: "Unit 25 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "Loan Lease",
    settlementPrice: 500000,
    settlementDate: "2022-03-04",
    marketValue: 620000,
    yearsOwned: 4.01,
    dmfRate: 0.03,
    annualDmf: 18600,
    totalDeferred: 74503.33,
    careAlertPhone: "0401 913 272",
    ownerName: "Wendy Ducrow (Jim passed away 18/04/25)",
    gender: "F",
    dob: "1945-05-30",
    age: "80.82191780821918",
    numResidents: 1,
    photos: ["/assets/photos/U25-JimandWendyDucrow.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "26",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 185.06,
    address: "Unit 26 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "C",
    settlementPrice: 387500,
    settlementDate: "2009-05-27",
    marketValue: 680000,
    yearsOwned: 16.77,
    dmfRate: 0.025,
    annualDmf: 0,
    nonAccDmf: 20400,
    totalDeferred: 170000,
    careAlertPhone: "0401 901 486",
    ownerName: "Annette Ward",
    gender: "F",
    dob: "1948-03-27",
    age: "77.9945205479452",
    numResidents: 1,
    photos: ["/assets/photos/U26-AnnetteWard.JPEG"],
    medicalFiles: ["/assets/medical/Unit26.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "27",
    status: "Occupied",
    unitType: "2 Bedroom + Garage",
    unitStyle: "Contemporary",
    landSqm: 156.56,
    address: "Unit 27 26 Barrina Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "New",
    settlementPrice: 575000,
    settlementDate: "2024-08-09",
    marketValue: 620000,
    yearsOwned: 1.57,
    dmfRate: 0.03,
    annualDmf: 18600,
    totalDeferred: 29295,
    careAlertPhone: "0401 900 968",
    ownerName: "Christopher & Felicity Adderley",
    gender: "M&F",
    dob: "Chris - 8/08/1940 & Felicity -03/02/1942",
    age: "84 & 82",
    numResidents: 1,
    medicalFiles: ["/assets/medical/Unit27.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "28",
    status: "Occupied",
    unitType: "2 Bedroom + Garage",
    unitStyle: "Contemporary",
    landSqm: 155.98,
    address: "Unit 28 24 Highfield Avenue",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "C",
    settlementPrice: 448000,
    settlementDate: "2014-10-01",
    marketValue: 620000,
    yearsOwned: 11.43,
    dmfRate: 0.03,
    annualDmf: 0,
    nonAccDmf: 18600,
    totalDeferred: 186000,
    careAlertPhone: "0401 889 789",
    ownerName: "Jean Jansen",
    gender: "F",
    dob: "1936-03-31",
    age: "89.99178082191781",
    numResidents: 1,
    medicalFiles: ["/assets/medical/Unit28.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "29",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 191.39,
    address: "Unit 29 24 Highfield Avenue",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "D",
    settlementPrice: 680000,
    settlementDate: "2020-04-07",
    marketValue: 750000,
    yearsOwned: 5.91,
    dmfRate: 0.03,
    annualDmf: 22500,
    totalDeferred: 133062.5,
    careAlertPhone: "0401 886 435",
    ownerName: "Francis Egan",
    gender: "M",
    dob: "1943-12-03",
    age: "85",
    numResidents: 1,
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "30",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 211.25,
    address: "Unit 30 24 Highfield Avenue",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "C",
    settlementPrice: 492000,
    settlementDate: "2011-06-30",
    marketValue: 680000,
    yearsOwned: 14.68,
    dmfRate: 0.03,
    annualDmf: 0,
    nonAccDmf: 20400,
    totalDeferred: 204000,
    careAlertPhone: "0401 886 191",
    ownerName: "Margaret Murphy",
    gender: "F",
    dob: "1932-03-05",
    age: "94.06575342465753",
    numResidents: 1,
    photos: ["/assets/photos/U30-MargaretMurphy.JPEG"],
    medicalFiles: ["/assets/medical/Unit30.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "31",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 245.08,
    address: "Unit 31 24 Highfield Avenue",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "New",
    settlementPrice: 670000,
    settlementDate: "2023-09-15",
    marketValue: 750000,
    yearsOwned: 2.48,
    dmfRate: 0.03,
    annualDmf: 22500,
    totalDeferred: 55687.5,
    careAlertPhone: "0401 913 097",
    ownerName: "Ruth Ryall",
    gender: "F",
    dob: "1944-11-15",
    age: "81.35890410958905",
    numResidents: 1,
    medicalFiles: ["/assets/medical/Unit31.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "32",
    status: "Occupied",
    unitType: "2 Bedroom + Garage",
    unitStyle: "Contemporary",
    landSqm: 184.05,
    address: "Unit 32 24 Highfield Avenue",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "Loan Lease",
    settlementPrice: 550000,
    settlementDate: "2024-04-18",
    marketValue: 620000,
    yearsOwned: 1.88,
    dmfRate: 0.03,
    annualDmf: 18600,
    totalDeferred: 35030,
    careAlertPhone: "0401 312 218",
    ownerName: "Danielle Snooks",
    gender: "F",
    dob: "1957-03-23",
    age: "69",
    numResidents: 1,
    medicalFiles: ["/assets/medical/Unit32.jpg", "/assets/medical/Unit32B.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "33",
    status: "Vacant",
    unitType: "2 Bedroom + Garage",
    unitStyle: "Contemporary",
    landSqm: 161.33,
    address: "Unit 33 24 Highfield Avenue",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "C",
    settlementPrice: 455000,
    settlementDate: "2013-03-27",
    marketValue: 620000,
    yearsOwned: 12.94,
    dmfRate: 0.03,
    annualDmf: 0,
    nonAccDmf: 18600,
    totalDeferred: 186000,
    careAlertPhone: "0401 910 653",
    ownerName: "Neville Houghton  (Deceased)",
    gender: "M",
    dob: "1927-08-04",
    age: "98.65479452054795",
    numResidents: 1,
    comments: "SOLD - Bert & Barbara @ 620k\nSettles - 8th April 2026\nChris son 0417 568 158",
    photos: ["/assets/photos/U33-NevilleHoughton.JPEG"],
    medicalFiles: ["/assets/medical/Unit33.jpg"],
    isDeceased: true,
    isForSale: true,
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "34",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 183.33,
    address: "Unit 34 24 Highfield Avenue",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "New",
    settlementPrice: 700000,
    settlementDate: "2025-01-17",
    marketValue: 700000,
    yearsOwned: 1.14,
    dmfRate: 0.03,
    annualDmf: 21000,
    totalDeferred: 23858.33,
    careAlertPhone: "0401 910 423",
    ownerName: "Eric & Frances (Fran) Davidson",
    gender: "M&F",
    dob: "01/11/1940 & 28/12/1940",
    age: "85 & 85",
    numResidents: 2,
    photos: ["/assets/photos/U34-BarbaraLord.JPEG"],
    medicalFiles: ["/assets/medical/Unit34.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "35",
    status: "Occupied",
    unitType: "2 Bedroom + Garage",
    unitStyle: "Contemporary",
    landSqm: 211.31,
    address: "Unit 35 24 Highfield Avenue",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "New",
    settlementPrice: 530000,
    settlementDate: "2023-09-22",
    marketValue: 620000,
    yearsOwned: 2.46,
    dmfRate: 0.03,
    annualDmf: 18600,
    totalDeferred: 45673.33,
    careAlertPhone: "0401 913 097",
    ownerName: "Margaret Dupont",
    gender: "F",
    dob: "1939-06-20",
    age: "86.76986301369863",
    numResidents: 1,
    photos: ["/assets/photos/U35-MargaretDupont.jpg"],
    medicalFiles: ["/assets/medical/Unit35.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "36",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 213.54,
    address: "Unit 36 24 Highfield Avenue",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "New",
    settlementPrice: 720000,
    settlementDate: "2025-09-18",
    marketValue: 720000,
    yearsOwned: 0.47,
    dmfRate: 0.03,
    annualDmf: 21600,
    totalDeferred: 10080,
    careAlertPhone: "0401 932 353",
    ownerName: "Averil Colomb ",
    gender: "F",
    dob: "",
    age: "126.26575342465753",
    numResidents: 1,
    medicalFiles: ["/assets/medical/Unit36.jpg", "/assets/medical/Unit36B.jpg", "/assets/medical/Unit36C.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "37",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 194.6,
    address: "Unit 37 24 Highfield Avenue",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "Loan Lease",
    settlementPrice: 741390,
    settlementDate: "2024-08-12",
    marketValue: 700000,
    yearsOwned: 1.57,
    dmfRate: 0.03,
    annualDmf: 21000,
    totalDeferred: 32900,
    careAlertPhone: "0401 850 403",
    ownerName: "Michael Papworth & Heather Davey ",
    gender: "M&F",
    dob: "03/10/1939 & 4/01/1942",
    age: "86 & 83",
    numResidents: 2,
    medicalFiles: ["/assets/medical/Unit37.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "38",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 201.36,
    address: "Unit 38 24 Highfield Avenue",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "C",
    settlementPrice: 484000,
    settlementDate: "2012-10-01",
    marketValue: 700000,
    yearsOwned: 13.43,
    dmfRate: 0.03,
    annualDmf: 0,
    nonAccDmf: 21000,
    totalDeferred: 210000,
    careAlertPhone: "0401 847 366",
    ownerName: "Jim O'Farrell (Deceased)",
    gender: "M",
    dob: "1939-10-23",
    age: "86.42739726027398",
    numResidents: 1,
    comments: "UNDER OFFER - Kath 700k plus 100k for fully renovation",
    medicalFiles: ["/assets/medical/Unit38.jpg"],
    isDeceased: true,
    isForSale: true,
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "39",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 186.18,
    address: "Unit 39 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "Loan Lease",
    settlementPrice: 748682.84,
    settlementDate: "2023-05-04",
    marketValue: 750000,
    yearsOwned: 2.84,
    dmfRate: 0.03,
    annualDmf: 22500,
    totalDeferred: 63875.0,
    careAlertPhone: "0401 845 599",
    ownerName: "Gwen Chaplin",
    gender: "F",
    dob: "1935-07-09",
    age: "90.72054794520548",
    numResidents: 1,
    photos: ["/assets/photos/U39-GwenChaplin.jpg"],
    medicalFiles: ["/assets/medical/Unit39.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "40",
    status: "Occupied",
    unitType: "2 Bedroom + Garage",
    unitStyle: "Contemporary",
    landSqm: 174.11,
    address: "Unit 40 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "D",
    settlementPrice: 500000,
    settlementDate: "2018-08-21",
    marketValue: 620000,
    yearsOwned: 7.54,
    dmfRate: 0.03,
    annualDmf: 18600,
    totalDeferred: 140275,
    careAlertPhone: "0401 844 662",
    ownerName: "Yvonne Garside",
    gender: "F",
    dob: "1934-01-10",
    age: "92.21369863013699",
    numResidents: 1,
    photos: ["/assets/photos/U40-YvonneGarside.JPEG"],
    medicalFiles: ["/assets/medical/Unit40.jpg", "/assets/medical/Unit40B.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "41",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 193.77,
    address: "Unit 41 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "D",
    settlementPrice: 543000,
    settlementDate: "2018-04-24",
    marketValue: 680000,
    yearsOwned: 7.87,
    dmfRate: 0.03,
    annualDmf: 20400,
    totalDeferred: 160480.0,
    careAlertPhone: "0401 843 639",
    ownerName: "Barbara Coward",
    gender: "F",
    dob: "1944-03-12",
    age: "82.03835616438356",
    numResidents: 1,
    photos: ["/assets/photos/U41-BarbaraCoward.JPEG"],
    medicalFiles: ["/assets/medical/Unit41.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "42",
    status: "Vacant",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 203.57,
    address: "Unit 42 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "D",
    settlementPrice: 496000,
    settlementDate: "2016-01-25",
    marketValue: 700000,
    yearsOwned: 10.11,
    dmfRate: 0.03,
    annualDmf: 0,
    nonAccDmf: 21000,
    totalDeferred: 210000,
    careAlertPhone: "0401 840 831",
    ownerName: "Marge Ward (Deceased)",
    gender: "F",
    dob: "1933-02-03",
    age: "93.14794520547945",
    numResidents: 1,
    comments: "For Sale\nKingsley \u2013 0426 978 403 (son in-law \u2013 Anthea husband); k.watkins@smartchat.net.au\nAnthea \u2013 0403 574 064 (daughter)\nDeborah \u2013 0419 556 263 (daughter)",
    photos: ["/assets/photos/U42-MargeWard.JPEG"],
    medicalFiles: ["/assets/medical/Unit42.jpg"],
    isDeceased: true,
    isForSale: true,
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "43",
    status: "Occupied",
    unitType: "2 Bedroom + Garage",
    unitStyle: "Contemporary",
    landSqm: 152.07,
    address: "Unit 43 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "New",
    settlementPrice: 600000,
    settlementDate: "2024-06-17",
    marketValue: 620000,
    yearsOwned: 1.72,
    dmfRate: 0.03,
    annualDmf: 18600,
    totalDeferred: 31981.67,
    careAlertPhone: "0401 841 296",
    ownerName: "Janet & Chris",
    gender: "M&F",
    dob: "Chris: 30/12/1946 & Janet: 14/04/1947",
    age: "78 & 77",
    numResidents: 2,
    photos: ["/assets/photos/U43-BillandShirleyCole.jpg", "/assets/photos/U43-BillCole.JPEG", "/assets/photos/U43-ShirleyCole.JPEG"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "44",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 165.87,
    address: "Unit 44 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "D",
    settlementPrice: 570000,
    settlementDate: "2021-03-05",
    marketValue: 680000,
    yearsOwned: 5.0,
    dmfRate: 0.03,
    annualDmf: 20400,
    totalDeferred: 102056.67,
    careAlertPhone: "0401 838 934",
    ownerName: "Keith & Sheila McAllister",
    gender: "M&F",
    dob: "Keith 1/3/1935 & Sheila 3/10/1931",
    age: "#VALUE!",
    numResidents: 2,
    photos: ["/assets/photos/U44-KeithandSheilaMcAllister.jpg", "/assets/photos/U44-KeithMcAllister.JPEG", "/assets/photos/U44-SheilaMcAllister.JPEG"],
    medicalFiles: ["/assets/medical/Unit44.jpg", "/assets/medical/Unit44B.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "45",
    status: "Occupied",
    unitType: "2 Bedroom + Garage",
    unitStyle: "Contemporary",
    landSqm: 139.31,
    address: "Unit 45 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "C",
    settlementPrice: 435000,
    settlementDate: "2015-06-05",
    marketValue: 620000,
    yearsOwned: 10.75,
    dmfRate: 0.03,
    annualDmf: 0,
    nonAccDmf: 18600,
    totalDeferred: 186000,
    careAlertPhone: "0401 832 645",
    ownerName: "Geoffrey Scash",
    gender: "M",
    dob: "1953-03-23",
    age: "73.0027397260274",
    numResidents: 1,
    photos: ["/assets/photos/U45-GeoffreyScash.JPEG"],
    medicalFiles: ["/assets/medical/Unit45.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "46",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 168.27,
    address: "Unit 46 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "Loan Lease",
    settlementPrice: 670000,
    settlementDate: "2023-12-14",
    marketValue: 750000,
    yearsOwned: 2.23,
    dmfRate: 0.03,
    annualDmf: 22500,
    totalDeferred: 50125,
    careAlertPhone: "0401 832 131",
    ownerName: "Mary (Beryl) & Chelliah (Kana) Kanagalinggam",
    gender: "M&F",
    dob: "29/08/1943 & 02/09/1943",
    age: "80 & 80",
    numResidents: 2,
    medicalFiles: ["/assets/medical/Unit46.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "47",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 189.39,
    address: "Unit 47 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "A",
    settlementPrice: 190000,
    settlementDate: "1999-10-31",
    marketValue: 680000,
    yearsOwned: 26.35,
    dmfRate: 0.025,
    annualDmf: 0,
    nonAccDmf: 20400,
    totalDeferred: 170000,
    careAlertPhone: "0401 828 654",
    ownerName: "Beverley Dundas",
    gender: "F",
    dob: "1938-11-11",
    age: "87.37534246575342",
    numResidents: 1,
    medicalFiles: ["/assets/medical/Unit47.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "48",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 220.24,
    address: "Unit 48 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "A",
    settlementPrice: 185000,
    settlementDate: "1999-10-14",
    marketValue: 680000,
    yearsOwned: 26.39,
    dmfRate: 0.025,
    annualDmf: 0,
    nonAccDmf: 20400,
    totalDeferred: 170000,
    careAlertPhone: "0401 826 182",
    ownerName: "Harold & Lesley Renton (Harold Deseased)",
    gender: "M&F",
    dob: "24/11/1925 & 24/06/1934",
    age: "100",
    numResidents: 2,
    photos: ["/assets/photos/U48-Haroldrenton.JPEG", "/assets/photos/U48-LesleyRenton.JPEG"],
    medicalFiles: ["/assets/medical/Unit48.jpg", "/assets/medical/Unit48B.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "49",
    status: "Occupied",
    unitType: "2 Bedroom + Garage",
    unitStyle: "Contemporary",
    landSqm: 156.84,
    address: "Unit 49 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "D",
    settlementPrice: 500000,
    settlementDate: "2021-07-12",
    marketValue: 620000,
    yearsOwned: 4.65,
    dmfRate: 0.03,
    annualDmf: 18600,
    totalDeferred: 86490,
    careAlertPhone: "0401 825 485",
    ownerName: "Margret Armstrong",
    gender: "F",
    dob: "1934-01-28",
    age: "92.16438356164383",
    numResidents: 1,
    photos: ["/assets/photos/U49-MargaretArmstrong.JPEG"],
    medicalFiles: ["/assets/medical/Unit49.pdf"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "50",
    status: "Occupied",
    unitType: "2 Bedroom + Garage",
    unitStyle: "Contemporary",
    landSqm: 189.58,
    address: "Unit 50 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "A",
    settlementPrice: 290000,
    settlementDate: "2003-11-28",
    marketValue: 620000,
    yearsOwned: 22.27,
    dmfRate: 0.025,
    annualDmf: 0,
    nonAccDmf: 18600,
    totalDeferred: 155000,
    careAlertPhone: "0401 824 056",
    ownerName: "Ken & Beryl Pakes",
    gender: "M&F",
    dob: "4/8/31 & 13/7/33",
    age: "93 & 91",
    numResidents: 2,
    medicalFiles: ["/assets/medical/Unit50.jpg", "/assets/medical/Unit50B.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "51",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 194.58,
    address: "Unit 51 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "D",
    settlementPrice: 524000,
    settlementDate: "2017-01-20",
    marketValue: 680000,
    yearsOwned: 9.13,
    dmfRate: 0.03,
    annualDmf: 20400,
    totalDeferred: 186206.67,
    careAlertPhone: "0401 182 303",
    ownerName: "Jean Holloway",
    gender: "F",
    dob: "1932-03-27",
    age: "94.0054794520548",
    numResidents: 1,
    medicalFiles: ["/assets/medical/Unit51.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "52",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 188.24,
    address: "Unit 52 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "Loan Lease",
    settlementPrice: 700000,
    settlementDate: "2023-01-11",
    marketValue: 700000,
    yearsOwned: 3.15,
    dmfRate: 0.03,
    annualDmf: 21000,
    totalDeferred: 66208.33,
    careAlertPhone: "0401 822 414",
    ownerName: "Len & Julia Fuller",
    gender: "M&F",
    dob: "08/09/37 & 14/08/40",
    age: "85 & 82",
    numResidents: 2,
    photos: ["/assets/photos/U52-LenandJuliaFuller.jpg"],
    medicalFiles: ["/assets/medical/Unit52.jpg", "/assets/medical/Unit52B.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "53",
    status: "Occupied",
    unitType: "2 Bedroom + Garage",
    unitStyle: "Contemporary",
    landSqm: 157.28,
    address: "Unit 53 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "C",
    settlementPrice: 435000,
    settlementDate: "2015-04-01",
    marketValue: 620000,
    yearsOwned: 10.93,
    dmfRate: 0.03,
    annualDmf: 0,
    nonAccDmf: 18600,
    totalDeferred: 186000,
    careAlertPhone: "0401 818 803",
    ownerName: "Allan & Joyce Lomer (Joyce passed away 23/01/23)",
    gender: "M",
    dob: "2029-12-29",
    age: "96",
    numResidents: 1,
    photos: ["/assets/photos/U53-AllanLomer.JPEG"],
    medicalFiles: ["/assets/medical/Unit53.jpg", "/assets/medical/Unit53B.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "54",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 193.17,
    address: "Unit 54 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "Strata",
    settlementPrice: 660000,
    settlementDate: "2024-10-04",
    marketValue: 680000,
    yearsOwned: 1.42,
    dmfRate: 0.03,
    annualDmf: 20400,
    totalDeferred: 29013.33,
    careAlertPhone: "0401 818 418",
    ownerName: "CJ & Maggie Luke",
    gender: "F",
    dob: "01/06/1951 & 26/04/1946",
    age: "73 & 78",
    numResidents: 2,
    photos: ["/assets/photos/U54-JimBurrowes.JPEG"],
    medicalFiles: ["/assets/medical/Unit54.jpg", "/assets/medical/Unit54B.jpg", "/assets/medical/Unit54C.jpg", "/assets/medical/Unit54D.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "55",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 187.81,
    address: "Unit 55 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "Loan Lease",
    settlementPrice: 575000,
    settlementDate: "2022-02-21",
    marketValue: 680000,
    yearsOwned: 4.04,
    dmfRate: 0.03,
    annualDmf: 20400,
    totalDeferred: 82450,
    careAlertPhone: "0401 816 553",
    ownerName: "Cathy Manners",
    gender: "F",
    dob: "1962-07-24",
    age: "63.66027397260274",
    numResidents: 1,
    medicalFiles: ["/assets/medical/Unit55.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "56",
    status: "Occupied",
    unitType: "2 Bedroom + Garage",
    unitStyle: "Contemporary",
    landSqm: 167.46,
    address: "Unit 56 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "Strata",
    settlementPrice: 610000,
    settlementDate: "2025-01-24",
    marketValue: 620000,
    yearsOwned: 1.12,
    dmfRate: 0.03,
    annualDmf: 18600,
    totalDeferred: 20770,
    careAlertPhone: "0401 816 206",
    ownerName: "Graham & Shirley Moxham",
    gender: "M&F",
    dob: "27/03/1946 & 08/12/1946",
    age: "78 & 78",
    numResidents: 1,
    medicalFiles: ["/assets/medical/Unit56.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "57",
    status: "Occupied",
    unitType: "2 Bedroom + Study + Garage",
    unitStyle: "Contemporary",
    landSqm: 180.02,
    address: "Unit 57 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "Strata",
    settlementPrice: 660000,
    settlementDate: "2024-01-25",
    marketValue: 680000,
    yearsOwned: 2.11,
    dmfRate: 0.03,
    annualDmf: 20400,
    totalDeferred: 43123.33,
    careAlertPhone: "0401 813 209",
    ownerName: "Anthony (Tony) Douge",
    gender: "F",
    dob: "1954-11-16",
    age: "71.35068493150685",
    numResidents: 1,
    medicalFiles: ["/assets/medical/Unit57.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "58",
    status: "Vacant",
    unitType: "1 Bedroom",
    unitStyle: "Contemporary",
    landSqm: 90.19,
    address: "Unit 58 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "N/A",
    settlementPrice: 250000,
    settlementDate: "2022-07-14",
    marketValue: 395000,
    yearsOwned: 3.64,
    dmfRate: 0,
    annualDmf: 0,
    totalDeferred: 0,
    careAlertPhone: "0401 811 770",
    ownerName: "BGP Owned - Leased to: Pat Convy  (Deceased)",
    gender: "F",
    dob: "1947-12-04",
    age: "78.30684931506849",
    numResidents: 1,
    comments: "For Sale",
    isDeceased: true,
    isForSale: true,
    residents: [],
    notes: [],
    fieldHistory: [],
  },
  {
    unitNo: "59",
    status: "Occupied",
    unitType: "1 Bedroom",
    unitStyle: "Contemporary",
    landSqm: 79.83,
    address: "Unit 59 40 Donald Street",
    suburb: "Blackburn South",
    state: "VIC",
    postcode: "3130",
    ownership: "Strata",
    contractType: "D",
    settlementPrice: 277000,
    settlementDate: "2019-10-24",
    marketValue: 395000,
    yearsOwned: 6.37,
    dmfRate: 0.03,
    annualDmf: 11850,
    totalDeferred: 75445.0,
    careAlertPhone: "0401 810 855",
    ownerName: "Anne Ahles",
    gender: "F",
    dob: "1955-05-11",
    age: "70.86849315068493",
    numResidents: 1,
    medicalFiles: ["/assets/medical/Unit59.jpg"],
    residents: [],
    notes: [],
    fieldHistory: [],
  },
];

export const simCards: SimCard[] = [
  {
    unitNo: "1",
    residentName: "Eustace (Bill) & Shirley Cole",
    mobileNumber: "0401 909 506",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "2",
    residentName: "Kevin Stewart",
    mobileNumber: "0401 932 815",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "3",
    residentName: "Anthony (Tony) Castellano",
    mobileNumber: "0401 972 050",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "4",
    residentName: "Geoffrey Auton",
    mobileNumber: "0401 971 941",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "5",
    residentName: "Dianne Leslie",
    mobileNumber: "0401 969 740",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "7",
    residentName: "Myf Macfarlane ",
    mobileNumber: "0401 969 390",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "8",
    residentName: "Cheryl Dabrera",
    mobileNumber: "0401 968 388",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "9",
    residentName: "Margaret White",
    mobileNumber: "0401 967 501",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "10",
    residentName: "Lesley Soxsmith",
    mobileNumber: "0401 934 760",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "11",
    residentName: "Maree Wright",
    mobileNumber: "0401 932 001",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "12",
    residentName: "Carole & Meriel Barber",
    mobileNumber: "0401 930 455",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "13",
    residentName: "Lucy Lynch",
    mobileNumber: "0401 927 229",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "14",
    residentName: "Lucy Ferris",
    mobileNumber: "0401 922 614",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "15",
    residentName: "Ilona Mc Lauchlan",
    mobileNumber: "0401 908 530",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "16",
    residentName: "Kaye Wood",
    mobileNumber: "0401 960 975",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "17",
    residentName: "Sheila Turner",
    mobileNumber: "0401 930 063",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "18",
    residentName: "Mary Gledhill",
    mobileNumber: "0401 906 217",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "19",
    residentName: "Clive & Jeanne Williams",
    mobileNumber: "0401 906 068",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "20",
    residentName: "Elizabeth Lawrence",
    mobileNumber: "0401 885 570",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "21",
    residentName: "Edna Lee",
    mobileNumber: "0401 929 068",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "22",
    residentName: "Vyvyan Nielsen",
    mobileNumber: "0401 922 047",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "23",
    residentName: "Henry Thorburn (higher care)",
    mobileNumber: "0401 920 624",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "25",
    residentName: "Wendy Ducrow (Jim passed away 18/04/25)",
    mobileNumber: "0401 913 272",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "26",
    residentName: "Annette Ward",
    mobileNumber: "0401 901 486",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "27",
    residentName: "Christopher & Felicity Adderley",
    mobileNumber: "0401 900 968",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "28",
    residentName: "Jean Jansen",
    mobileNumber: "0401 889 789",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "29",
    residentName: "Francis Egan",
    mobileNumber: "0401 886 435",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "30",
    residentName: "Margaret Murphy",
    mobileNumber: "0401 886 191",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "31",
    residentName: "Ruth Ryall",
    mobileNumber: "0401 913 097",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "32",
    residentName: "Danielle Snooks",
    mobileNumber: "0401 312 218",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "34",
    residentName: "Eric & Frances (Fran) Davidson",
    mobileNumber: "0401 910 423",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "35",
    residentName: "Margaret Dupont",
    mobileNumber: "0401 913 097",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "36",
    residentName: "Averil Colomb ",
    mobileNumber: "0401 932 353",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "37",
    residentName: "Michael Papworth & Heather Davey ",
    mobileNumber: "0401 850 403",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "38",
    residentName: "Jim O'Farrell (Deceased)",
    mobileNumber: "0401 847 366",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "39",
    residentName: "Gwen Chaplin",
    mobileNumber: "0401 845 599",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "40",
    residentName: "Yvonne Garside",
    mobileNumber: "0401 844 662",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "41",
    residentName: "Barbara Coward",
    mobileNumber: "0401 843 639",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "43",
    residentName: "Janet & Chris",
    mobileNumber: "0401 841 296",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "44",
    residentName: "Keith & Sheila McAllister",
    mobileNumber: "0401 838 934",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "45",
    residentName: "Geoffrey Scash",
    mobileNumber: "0401 832 645",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "46",
    residentName: "Mary (Beryl) & Chelliah (Kana) Kanagalinggam",
    mobileNumber: "0401 832 131",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "47",
    residentName: "Beverley Dundas",
    mobileNumber: "0401 828 654",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "48",
    residentName: "Harold & Lesley Renton (Harold Deseased)",
    mobileNumber: "0401 826 182",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "49",
    residentName: "Margret Armstrong",
    mobileNumber: "0401 825 485",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "50",
    residentName: "Ken & Beryl Pakes",
    mobileNumber: "0401 824 056",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "51",
    residentName: "Jean Holloway",
    mobileNumber: "0401 182 303",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "52",
    residentName: "Len & Julia Fuller",
    mobileNumber: "0401 822 414",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "53",
    residentName: "Allan & Joyce Lomer (Joyce passed away 23/01/23)",
    mobileNumber: "0401 818 803",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "54",
    residentName: "CJ & Maggie Luke",
    mobileNumber: "0401 818 418",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "55",
    residentName: "Cathy Manners",
    mobileNumber: "0401 816 553",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "56",
    residentName: "Graham & Shirley Moxham",
    mobileNumber: "0401 816 206",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "57",
    residentName: "Anthony (Tony) Douge",
    mobileNumber: "0401 813 209",
    provider: 'Telstra',
    status: 'Active',
  },
  {
    unitNo: "59",
    residentName: "Anne Ahles",
    mobileNumber: "0401 810 855",
    provider: 'Telstra',
    status: 'Active',
  },
];

export const leads: Lead[] = [
  {
    id: "lead-1",
    firstName: "Patricia",
    lastName: "Morrison",
    phone: "0412 345 678",
    email: "p.morrison@email.com",
    address: "14 Oak Street, Ringwood VIC 3134",
    desiredUnitStyle: "2 Bedroom — Classic",
    budget: 550000,
    status: "Active",
    createdAt: "2026-01-15",
    leadSource: "Website",
    contactLog: [],
    notes: [],
    fieldHistory: [],
  },
  {
    id: "lead-2",
    firstName: "Robert",
    lastName: "Chambers",
    phone: "0423 456 789",
    email: "r.chambers@email.com",
    desiredUnitStyle: "2 Bedroom + Garage — Contemporary",
    budget: 680000,
    status: "Active",
    createdAt: "2026-02-03",
    leadSource: "Referral",
    contactLog: [],
    notes: [],
    fieldHistory: [],
  },
];

export const waitlist: WaitlistEntry[] = [
  {
    id: "wl-1",
    firstName: "Dorothy",
    lastName: "Hartley",
    phone: "0434 567 890",
    desiredUnitStyle: "2 Bedroom — Classic",
    budget: 520000,
    createdAt: "2025-11-20",
    notes: [],
    priority: 1,
  },
  {
    id: "wl-2",
    firstName: "Brian",
    lastName: "Sutherland",
    phone: "0445 678 901",
    desiredUnitStyle: "2 Bedroom + Study + Garage — Contemporary",
    budget: 700000,
    createdAt: "2025-12-10",
    notes: [],
    priority: 2,
  },
];

export const tasks: Task[] = [
  {
    id: "task-1",
    title: "Follow up Unit 24 sale settlement",
    description: "Unit 24 settles 23rd April 2026. Confirm with Lisa (Derik son) re 550k.",
    status: "Open",
    priority: "High",
    category: "Sales",
    assignedTo: "Sam Elsha",
    dueDate: "2026-04-23",
    createdAt: "2026-03-06",
    relatedTo: "Unit 24",
    relatedType: "unit",
    notes: [],
  },
  {
    id: "task-2",
    title: "Follow up Unit 33 sale settlement",
    description: "Unit 33 settles 8th April 2026. Bert & Barbara @ 620k. Chris son 0417 568 158.",
    status: "Open",
    priority: "High",
    category: "Sales",
    assignedTo: "Sam Elsha",
    dueDate: "2026-04-08",
    createdAt: "2026-03-06",
    relatedTo: "Unit 33",
    relatedType: "unit",
    notes: [],
  },
  {
    id: "task-3",
    title: "Unit 38 renovation quote",
    description: "Unit 38 under offer — Kath 700k plus 100k for full renovation. Get renovation quote.",
    status: "Open",
    priority: "High",
    category: "Maintenance",
    assignedTo: "Katherine Connick",
    dueDate: "2026-03-20",
    createdAt: "2026-03-06",
    relatedTo: "Unit 38",
    relatedType: "unit",
    notes: [],
  },
];

export const maintenanceRequests: MaintenanceRequest[] = [
  {
    id: "maint-1",
    unitNo: "38",
    title: "Full unit renovation",
    description: "Unit 38 requires full renovation prior to resale. Kath 700k + 100k renovation.",
    status: "Logged",
    priority: "High",
    reportedBy: "Sam Elsha",
    createdAt: "2026-03-06",
    notes: [],
  },
  {
    id: "maint-2",
    unitNo: "6",
    title: "Renovation management",
    description: "Unit 6 (BGP Owned) — renovation management required before resale.",
    status: "In Progress",
    priority: "Medium",
    reportedBy: "Sam Elsha",
    createdAt: "2026-02-01",
    notes: [],
  },
];

export const appointments: Appointment[] = [
  {
    id: "appt-1",
    title: "Village Tour — Patricia Morrison",
    type: "Village Tour",
    date: "2026-03-12",
    time: "10:00",
    contactName: "Patricia Morrison",
    contactPhone: "0412 345 678",
    contactEmail: "p.morrison@email.com",
    location: "26 Barrina Street, Blackburn South",
    createdBy: "Sam Elsha",
    createdAt: "2026-03-06",
  },
];

export interface UpcomingSale {
  unitNo: string;
  owner: string;
  unitType: string;
  sellPrice: number;
  dmfRate: number;
  yearsOwned: number;
  dmfTotal: number;
  dmfDollars: number;
  sellFeeBGM?: number;
  sellFeeMngrs?: number;
  extra?: number;
  extraNotes?: string;
}

export const upcomingSales: UpcomingSale[] = [
  {
    unitNo: "6",
    owner: "BGP Owned",
    unitType: "1 Bedroom",
    sellPrice: 395000,
    dmfRate: 0,
    yearsOwned: 3.67,
    dmfTotal: 0,
    dmfDollars: 395000,
    extra: 15000,
    extraNotes: "Renovation Management",
  },
  {
    unitNo: "23",
    owner: "Henry Thorburn (higher care)",
    unitType: "2 Bedroom",
    sellPrice: 575000,
    dmfRate: 0.03,
    yearsOwned: 8.82,
    dmfTotal: 0.2645,
    dmfDollars: 152087.5,
    sellFeeBGM: 9583.33,
    sellFeeMngrs: 4791.67,
    extra: 16000,
    extraNotes: "Renovation Management",
  },
  {
    unitNo: "24",
    owner: "Kay Allan (Deceased)",
    unitType: "2 Bedroom",
    sellPrice: 550000,
    dmfRate: 0.03,
    yearsOwned: 10,
    dmfTotal: 0.3,
    dmfDollars: 165000,
    sellFeeBGM: 9166.67,
    sellFeeMngrs: 4583.33,
    extraNotes: "Renovation Profit",
  },
  {
    unitNo: "33",
    owner: "Neville Houghton  (Deceased)",
    unitType: "2 Bedroom + Garage",
    sellPrice: 620000,
    dmfRate: 0.03,
    yearsOwned: 10,
    dmfTotal: 0.3,
    dmfDollars: 186000,
    sellFeeBGM: 10333.33,
    sellFeeMngrs: 5166.67,
  },
  {
    unitNo: "38",
    owner: "Jim O'Farrell (Deceased)",
    unitType: "2 Bedroom + Study + Garage",
    sellPrice: 700000,
    dmfRate: 0.03,
    yearsOwned: 10,
    dmfTotal: 0.3,
    dmfDollars: 210000,
    sellFeeBGM: 11666.67,
    sellFeeMngrs: 5833.33,
    extra: 22000,
    extraNotes: "Renovation Management",
  },
  {
    unitNo: "42",
    owner: "Marge Ward (Deceased)",
    unitType: "2 Bedroom + Study + Garage",
    sellPrice: 700000,
    dmfRate: 0.03,
    yearsOwned: 10,
    dmfTotal: 0.3,
    dmfDollars: 210000,
    sellFeeBGM: 11666.67,
    sellFeeMngrs: 5833.33,
  },
  {
    unitNo: "58",
    owner: "BGP Owned - Leased to: Pat Convy  (Deceased)",
    unitType: "1 Bedroom",
    sellPrice: 395000,
    dmfRate: 0,
    yearsOwned: 3.64,
    dmfTotal: 0,
    dmfDollars: 395000,
  },
];

export function getUnitByNo(unitNo: string): Unit | undefined {
  return units.find(u => u.unitNo === unitNo);
}

export function getOccupiedUnits(): Unit[] {
  return units.filter(u => u.status === 'Occupied');
}

export function getVacantUnits(): Unit[] {
  return units.filter(u => u.status === 'Vacant');
}

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD", maximumFractionDigits: 0 }).format(amount);
}

export function formatDMFRate(rate: number): string {
  return `${(rate * 100).toFixed(1)}%`;
}

export function calcAge(dob?: string): number {
  if (!dob) return 0;
  try {
    const birth = new Date(dob);
    if (isNaN(birth.getTime())) return 0;
    const today = new Date();
    let age = today.getFullYear() - birth.getFullYear();
    const m = today.getMonth() - birth.getMonth();
    if (m < 0 || (m === 0 && today.getDate() < birth.getDate())) age--;
    return age;
  } catch { return 0; }
}

export function formatDate(dateStr: string): string {
  if (!dateStr) return "—";
  try {
    const d = new Date(dateStr);
    return d.toLocaleDateString("en-AU", { day: "2-digit", month: "short", year: "numeric" });
  } catch { return dateStr; }
}

export const UNIT_STYLES = [
  "1 Bedroom — Classic",
  "1 Bedroom — Contemporary",
  "2 Bedroom — Classic",
  "2 Bedroom — Open Plan",
  "2 Bedroom — Contemporary",
  "2 Bedroom + Carport — Classic",
  "2 Bedroom + Study — Classic",
  "2 Bedroom + Study + Carport — Classic",
  "2 Bedroom + Garage — Classic",
  "2 Bedroom + Garage — Open Plan",
  "2 Bedroom + Garage — Contemporary",
  "2 Bedroom + Study + Garage — Contemporary",
] as const;

export const BGM_BRAND = {
  green: "#4a7c2f",
  greenDark: "#3a6124",
  greenLight: "#5a9c3a",
  brown: "#5c3d1e",
  brownLight: "#7a5230",
  sidebar: "#1A2332",
  sidebarBorder: "#243040",
  primary: "#4a7c2f",
} as const;

// ── Dashboard Stats Helper ────────────────────────────────────────────────────
export function getDashboardStats() {
  const occupied = units.filter(u => u.status === 'Occupied').length;
  const vacant = units.filter(u => u.status === 'Vacant').length;
  const totalUnits = units.length;
  const occupancyRate = totalUnits > 0 ? Math.round((occupied / totalUnits) * 100) : 0;
  const totalDmf = units.reduce((s, u) => s + (u.totalDeferred || 0), 0);
  const totalMarketValue = units.filter(u => u.status === 'Occupied').reduce((s, u) => s + (u.marketValue || 0), 0);
  const activeLeads = leads.filter(l => l.status === 'Active').length;
  const waitlistLeads = leads.filter(l => l.status === 'Waitlist').length;
  return {
    occupied, vacant, totalUnits, occupancyRate,
    totalDmf, totalMarketValue, activeLeads, waitlistLeads,
  };
}
